kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: helloworld 
  name:
    poc-helloworld
spec:
  replicas: 2
  selector:
    matchLabels:
      app: poc-helloworld
  template:
    metadata:
      labels:
        app: poc-helloworld
    spec:
      containers:
        - name: poc-helloworld
          image: azegistry.azurecr.io/poc-helloworld:VERSION-SHA
          env:
          - name: BUILD
            value: "VERSION"     
          - name: AZURE_STORAGE_CONTAINER_NAME
            value: "builds"  
          - name: AZURE_STORAGE_CONNECTION_STRING   
            value: "DefaultEndpointsProtocol=https;AccountName=numberbuilds;AccountKey=Yl6bVH/iNARuXxB9ztDfpR36FagkN52usFVFE9lrlGIslxYA/kg8lVYnQjdxXYbrpwQ8Aue2KDYZ+ASt6xxB0Q==;EndpointSuffix=core.windows.net"
          ports:
          - containerPort: 80
            name: poc-helloworld          
---
apiVersion: v1
kind: Service
metadata:
  namespace: helloworld
  name: poc-helloworld
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: poc-helloworld
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: helloworld
  name: hello-world-ingress-static
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: poc-helloworld
            port: 
              number: 80