kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: helloworld
  name:
    poc-helloworld
spec:
  replicas: 2
  selector:
    matchLabels:
      app: poc-helloworld
  template:
    metadata:
      labels:
        app: poc-helloworld
    spec:
      containers:
        - name: poc-helloworld
          image: IMAGE_REPO:VERSION
          env:
          - name: BUILD
            value: "VERSION"           
          ports:
          - containerPort: 80
            name: poc-helloworld          
---
apiVersion: v1
kind: Service
metadata:
  name: poc-helloworld
spec:
  ports:
  - port: 80
  selector:
    app: poc-helloworld
---
apiVersion: v1
kind: Service
metadata:
  name: poc-helloworld
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: poc-helloworld    
        