apiVersion: v1
kind: Pod
metadata:
  name: s3fs-app
spec:
  volumes:
    - name: s3-bucket
      emptyDir: {}   # volume partagé entre init et app

    - name: fuse-device
      hostPath:
        path: /dev/fuse
        type: CharDevice

  initContainers:
    - name: s3-mounter
      image: quay.io/efrecon/s3fs:latest
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        capabilities:
          add: ["SYS_ADMIN", "DAC_READ_SEARCH"]
        allowPrivilegeEscalation: false
      env:
        - name: AWSACCESSKEYID
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: accessKey
        - name: AWSSECRETACCESSKEY
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: secretKey
      command:
        - "sh"
        - "-c"
        - |
          mkdir -p /mnt/s3
          s3fs my-bucket /mnt/s3 \
            -o url=https://s3.amazonaws.com \
            -o use_path_request_style \
            -o allow_other \
            -o nonempty
          # Garder le processus en vie tant que l'app tourne
          sleep 3600
      volumeMounts:
        - mountPath: /mnt/s3
          name: s3-bucket
        - mountPath: /dev/fuse
          name: fuse-device

  containers:
    - name: app
      image: debian:bookworm-slim
      command: ["sleep", "infinity"]
      securityContext:
        runAsUser: 1000    # ton user app
        runAsGroup: 1000
        allowPrivilegeEscalation: false
      volumeMounts:
        - mountPath: /data
          name: s3-bucket
















          # Base UBI 9
FROM registry.access.redhat.com/ubi9/ubi:9.3

# Installer dépendances et s3fs-fuse
RUN dnf install -y \
      epel-release \
      fuse \
      fuse-libs \
      s3fs-fuse \
    && dnf clean all

# Créer un utilisateur applicatif non-root
RUN useradd -m appuser

# Répertoire de montage
RUN mkdir /mnt/s3 && chown appuser:appuser /mnt/s3

USER appuser

ENTRYPOINT ["sleep", "infinity"]







          
