apiVersion: v1
kind: Pod
metadata:
  name: code-server-s3
spec:
  initContainers:
    - name: sync-config-down
      image: rclone/rclone:latest
      args:
        - sync
        - s3:my-bucket/config
        - /shared/config
        - --create-empty-src-dirs
        - -v
      env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: accessKey
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: secretKey
        - name: RCLONE_CONFIG_S3_TYPE
          value: "s3"
        - name: RCLONE_CONFIG_S3_PROVIDER
          value: "Other"
        - name: RCLONE_CONFIG_S3_ENDPOINT
          value: "https://your-scality-endpoint.com"
        - name: RCLONE_CONFIG_S3_FORCE_PATH_STYLE
          value: "true"
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      volumeMounts:
        - name: shared-config
          mountPath: /shared/config

  containers:
    # --- Sidecar rclone sync périodique ---
    - name: rclone-sync
      image: rclone/rclone:latest
      command:
        - sh
        - -c
        - |
          echo "Démarrage sync périodique..."
          while true; do
            echo "$(date): Sync config vers S3..."
            rclone sync /shared/config s3:my-bucket/config --exclude "*.tmp" --exclude "*.lock" -v
            echo "$(date): Sync terminé"
            sleep 300  # Sync toutes les 5min
          done
      env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: accessKey
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: secretKey
        - name: RCLONE_CONFIG_S3_TYPE
          value: "s3"
        - name: RCLONE_CONFIG_S3_PROVIDER
          value: "AWS"
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      volumeMounts:
        - name: shared-config
          mountPath: /shared/config

    # --- Code-server ---
    - name: code-server
      image: codercom/code-server:latest
      args:
        - --bind-addr=0.0.0.0:8080
        - --auth=password
        - --disable-telemetry
        - /workspace
      env:
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: code-server-secret
              key: password
        - name: SHELL
          value: /bin/bash
      ports:
        - containerPort: 8080
          name: http
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      volumeMounts:
        - name: workspace
          mountPath: /workspace
        - name: shared-config
          mountPath: /home/coder/.config
      readinessProbe:
        httpGet:
          path: /healthz
          port: 8080
        initialDelaySeconds: 15
        periodSeconds: 10
      livenessProbe:
        httpGet:
          path: /healthz
          port: 8080
        initialDelaySeconds: 30
        periodSeconds: 30
      resources:
        requests:
          memory: 512Mi
          cpu: 100m
        limits:
          memory: 2Gi
          cpu: 1000m

  volumes:
    - name: workspace
      emptyDir:
        sizeLimit: 10Gi
    - name: shared-config
      emptyDir:
        sizeLimit: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: code-server-service
spec:
  selector:
    app: code-server
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  type: ClusterIP

---
apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
type: Opaque
stringData:
  accessKey: "YOUR_S3_ACCESS_KEY"
  secretKey: "YOUR_S3_SECRET_KEY"

---
apiVersion: v1
kind: Secret
metadata:
  name: code-server-secret
type: Opaque
stringData:
  password: "your-code-server-password"
  
  
  

Variables à ajuster pour Scality :

RCLONE_CONFIG_S3_ENDPOINT : URL de votre Scality (ex: https://s3.votre-domaine.com)
RCLONE_CONFIG_S3_FORCE_PATH_STYLE : true (souvent requis pour S3 compatible)

Optionnel selon votre config Scality :
yaml- name: RCLONE_CONFIG_S3_REGION
  value: "us-east-1"  # ou votre région
- name: RCLONE_CONFIG_S3_V2_AUTH
  value: "true"  # si signature v2 requise
Pour tester la connectivité :
bashkubectl exec -it code-server-s3 -c rclone-sync -- rclone ls s3:my-bucket
Remplacez https://your-scality-endpoint.com par l'URL réelle de votre Scality S3.

  
******  
  
  
  
  apiVersion: v1
kind: Pod
metadata:
  name: code-server-s3
spec:
  initContainers:
    - name: sync-config-down
      image: rclone/rclone:latest
      args:
        - sync
        - s3:my-bucket/config
        - /shared/config
        - --create-empty-src-dirs
        - -v
      env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: accessKey
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: secretKey
        - name: RCLONE_CONFIG_S3_TYPE
          value: "s3"
        - name: RCLONE_CONFIG_S3_PROVIDER
          value: "AWS"
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      volumeMounts:
        - name: shared-config
          mountPath: /shared/config

  containers:
    # --- Sidecar rclone sync périodique ---
    - name: rclone-sync
      image: rclone/rclone:latest
      command:
        - sh
        - -c
        - |
          echo "Démarrage sync périodique..."
          while true; do
            echo "$(date): Sync config vers S3..."
            rclone sync /shared/config s3:my-bucket/config --exclude "*.tmp" --exclude "*.lock" -v
            echo "$(date): Sync terminé"
            sleep 300  # Sync toutes les 5min
          done
      env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: accessKey
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: secretKey
        - name: RCLONE_CONFIG_S3_TYPE
          value: "s3"
        - name: RCLONE_CONFIG_S3_PROVIDER
          value: "AWS"
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      volumeMounts:
        - name: shared-config
          mountPath: /shared/config

    # --- Code-server ---
    - name: code-server
      image: codercom/code-server:latest
      args:
        - --bind-addr=0.0.0.0:8080
        - --auth=password
        - --disable-telemetry
        - /workspace
      env:
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: code-server-secret
              key: password
        - name: SHELL
          value: /bin/bash
      ports:
        - containerPort: 8080
          name: http
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      volumeMounts:
        - name: workspace
          mountPath: /workspace
        - name: shared-config
          mountPath: /home/coder/.config
      readinessProbe:
        httpGet:
          path: /healthz
          port: 8080
        initialDelaySeconds: 15
        periodSeconds: 10
      livenessProbe:
        httpGet:
          path: /healthz
          port: 8080
        initialDelaySeconds: 30
        periodSeconds: 30
      resources:
        requests:
          memory: 512Mi
          cpu: 100m
        limits:
          memory: 2Gi
          cpu: 1000m

  volumes:
    - name: workspace
      emptyDir:
        sizeLimit: 10Gi
    - name: shared-config
      emptyDir:
        sizeLimit: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: code-server-service
spec:
  selector:
    app: code-server
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  type: ClusterIP

---
apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
type: Opaque
stringData:
  accessKey: "YOUR_S3_ACCESS_KEY"
  secretKey: "YOUR_S3_SECRET_KEY"

---
apiVersion: v1
kind: Secret
metadata:
  name: code-server-secret
type: Opaque
stringData:
  password: "your-code-server-password"


Cette version :
✅ Pas de FUSE/mount - Utilise uniquement rclone sync
✅ Pas de root - Tout en runAsNonRoot: true
✅ InitContainer - Récupère la config au démarrage
✅ Sync périodique - Sauvegarde automatique toutes les 5min
✅ emptyDir - Volume simple sans contraintes
Fonctionnement :

InitContainer télécharge la config S3 → volume partagé
Code-server démarre avec la config
Sidecar synchronise les changements vers S3

Les modifications de config seront persistées dans S3 avec un délai max de 5 minutes.
