name: HelloWorld Paralell Jobs

on:
  push:
    tags:
      - '*'
env:
  MYPAT: ${{ secrets.MYPAT }}
  SHA: ${{ github.sha }}
  IMAGE_REPO: ${{ secrets.ACR_NAME }}.azurecr.io/poc-helloworld

jobs:
  Build-TagPush-Deploy01:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.MYPAT }}
      - name: Build image
        env:
          ACR_NAME: ${{ secrets.ACR_NAME }}
        run: make build
      - name: Login to container registry
        env:
          SERVICE_PRINCIPAL_APP_ID: ${{ secrets.SERVICE_PRINCIPAL_APP_ID }}
          SERVICE_PRINCIPAL_SECRET: ${{ secrets.SERVICE_PRINCIPAL_SECRET }}
          SERVICE_PRINCIPAL_TENANT: ${{ secrets.SERVICE_PRINCIPAL_TENANT }}
          ACR_NAME: ${{ secrets.ACR_NAME }}
        run: make registry-login
      - name: Push image
        env:
          ACR_NAME: ${{ secrets.ACR_NAME }}
        run: make push
      - name: Get AKS credentials
        env:
          CLUSTER_RESOURCE_GROUP_NAME: ${{ secrets.CLUSTER_RESOURCE_GROUP_NAME }}
          CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
        run: |
          az aks get-credentials \
            --resource-group $CLUSTER_RESOURCE_GROUP_NAME \
            --name $CLUSTER_NAME \
            --overwrite-existing
      - name: Deploy application
        run: |
          VERSION=$(cat ./version)

          echo $VERSION
          echo $IMAGE_REPO
          echo $SHA  

          sed -i 's|IMAGE_REPO|$IMAGE_REPO|g; s/VERSION/$VERSION/g; s/SHA/$SHA/g' ./deployment.yaml
          cat ./deployment.yaml
          kubectl apply -f ./deployment.yaml
      - name: Increment version and commit tag for the next loop
        run: |
          cd $GITHUB_WORKSPACE 
          version=$(cat ./version) 
          echo "$(($version+1))" > ./version 
          git config user.email "f.boukezzoula@gmail.com" 
          git config user.name "BOUKEZZOULA Fouzi"
          git add .
          git commit -m "release version $(cat ./version)" && git push https://$MYPAT@github.com/fboukezzoula/helloworld.git HEAD:main
          git tag $(cat ./version) && git push https://$MYPAT@github.com/fboukezzoula/helloworld.git --tags

