name: HelloWorld Paralell Jobs

on: [push,workflow_dispatch]

env:
  MYPAT: ${{ secrets.MYPAT }}
  SHA: ${{ github.sha }}
  AZURE_STORAGE_CONTAINER_NAME: ${{ AZURE_STORAGE_CONTAINER_NAME }}
  AZURE_STORAGE_CONNECTION_STRING: ${{ AZURE_STORAGE_CONNECTION_STRING }}

jobs:
   Build-TagPush-Deploy01:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.MYPAT }}
      - name: Build image
        env:
          ACR_NAME: ${{ secrets.ACR_NAME }}
        run: make build
      - name: Login to container registry
        env:
          SERVICE_PRINCIPAL_APP_ID: ${{ secrets.SERVICE_PRINCIPAL_APP_ID }}
          SERVICE_PRINCIPAL_SECRET: ${{ secrets.SERVICE_PRINCIPAL_SECRET }}
          SERVICE_PRINCIPAL_TENANT: ${{ secrets.SERVICE_PRINCIPAL_TENANT }}
          ACR_NAME: ${{ secrets.ACR_NAME }}
        run: make registry-login
      - name: Push image
        env:
          ACR_NAME: ${{ secrets.ACR_NAME }}
        run: make push
      - name: Get AKS credentials
        env:
          CLUSTER_RESOURCE_GROUP_NAME: ${{ secrets.CLUSTER_RESOURCE_GROUP_NAME }}
          CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
        run: |
          az aks get-credentials \
            --resource-group $CLUSTER_RESOURCE_GROUP_NAME \
            --name $CLUSTER_NAME \
            --overwrite-existing
      - name: Deploy application
        env:
          ACR_NAME: ${{ secrets.ACR_NAME }}
        run: make deploy 
      - name: Increment version and commit tag for the next loop
        run: |
          cd $GITHUB_WORKSPACE 
          touch $GITHUB_WORKSPACE/builds/build_number_$(date '+%Y%m%d%H%M%S').txt 

          export AZURE_STORAGE_ACCOUNT=$AZURE_STORAGE_ACCOUNT
          export AZURE_STORAGE_ACCESS_KEY=$AZURE_STORAGE_ACCESS_KEY

          # Upload sample files to container
          az storage blob upload-batch \
              --pattern "build_number_*.txt" \
              --source . \
              --destination builds \
              --overwrite
              
          git config user.email "f.boukezzoula@gmail.com" 
          git config user.name "BOUKEZZOULA Fouzi"
          git pull && git add . 
          git commit -m "Launch parallel build-push-deploy jobs" && git push https://$MYPAT@github.com/fboukezzoula/helloworld.git HEAD:main     
               
   Build-TagPush-Deploy02:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.MYPAT }}
      - name: Build image
        env:
          ACR_NAME: ${{ secrets.ACR_NAME }}
        run: make build
      - name: Login to container registry
        env:
          SERVICE_PRINCIPAL_APP_ID: ${{ secrets.SERVICE_PRINCIPAL_APP_ID }}
          SERVICE_PRINCIPAL_SECRET: ${{ secrets.SERVICE_PRINCIPAL_SECRET }}
          SERVICE_PRINCIPAL_TENANT: ${{ secrets.SERVICE_PRINCIPAL_TENANT }}
          ACR_NAME: ${{ secrets.ACR_NAME }}
        run: make registry-login
      - name: Push image
        env:
          ACR_NAME: ${{ secrets.ACR_NAME }}
        run: make push
      - name: Get AKS credentials
        env:
          CLUSTER_RESOURCE_GROUP_NAME: ${{ secrets.CLUSTER_RESOURCE_GROUP_NAME }}
          CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
        run: |
          az aks get-credentials \
            --resource-group $CLUSTER_RESOURCE_GROUP_NAME \
            --name $CLUSTER_NAME \
            --overwrite-existing
      - name: Deploy application
        env:
          ACR_NAME: ${{ secrets.ACR_NAME }}
        run: make deploy 
      - name: Increment version and commit tag for the next loop
        run: |
          cd $GITHUB_WORKSPACE 
          touch $GITHUB_WORKSPACE/builds/build_number_$(date '+%Y%m%d%H%M%S').txt 

          export AZURE_STORAGE_ACCOUNT=$AZURE_STORAGE_ACCOUNT
          export AZURE_STORAGE_ACCESS_KEY=$AZURE_STORAGE_ACCESS_KEY

          # Upload sample files to container
          az storage blob upload-batch \
              --pattern "build_number_*.txt" \
              --source . \
              --destination builds \
              --overwrite

          git config user.email "f.boukezzoula@gmail.com" 
          git config user.name "BOUKEZZOULA Fouzi"
          git pull && git add . 
          git commit -m "Launch parallel build-push-deploy jobs" && git push https://$MYPAT@github.com/fboukezzoula/helloworld.git HEAD:main   
    